### ISSUE TITLE
Destinations are not picking from tenant sub accounts

### ISSUE THREAD

**Issue by chandeep2013** [saphanaacademy/generator-saphanaacademy-saas#4]
Hi Team,

I am trying to build a multi-tenant application by using the below series of videos on youtube.

https://www.youtube.com/watch?v=E816z61O_S8&list=PLkzo92owKnVx3Sh0nemX8GoSNzJGfsWJM&index=1&ab_channel=SAPHANAAcademy
 
The provider account has two destinations. The application is working as expected from the provider account.

Subscribed application from Tenant subaccount.

The tenant account has two destinations. Application is **not picking the destinations from the Tenant account**. It is picked from the Provider subaccount.

I have gone through most of the sap blogs, unfortunately, I didn't find the solution for this problem.

If the application has to pick the destinations from the tenant subaccount do we need to write the additional logic?
If yes, guide us on the steps to write or share the sample code with me?

Could you help me to resolve this issue?

Regards,
Chandeep

**Comment by saphanaacademy** [comment]
Hi Chandeep,

Thanks for watching the videos and reaching out.

You need to create destinations in each subscriber subaccount with **exactly the same name** as used by the application and this should work as long as you activated the destination service as a dependency in the saas registry.

The subscriber destinations take precedence over destinations defined on the provider subaccount.

If you still have issues perhaps you can share more details?

Regards,

Philip
SAP HANA Academy

**Comment by chandeep2013** [comment]
Hello Philip,

Thanks for the reply.

1. I have created two destinations in the provider subaccount.
2.  From mta.yaml file destination service has been created **- Name:** mysaas-cfapi.
3. I have added destination service on saas registry dependencies. Please check the below image. Correct me If I am doing worng.
![image](https://user-images.githubusercontent.com/37897145/157822408-cd9dfb35-6973-4ceb-9c59-aec6a32e7d33.png)

- I have created the same destinations (exactly same name) as provider.
- Still I can see the destinations are picking from provider only.

I didn't created any destination service on Tenant subaccount.

Regards,
Chamdeep

**Comment by saphanaacademy** [comment]
Hi Chamdeep,

There's no need to create an instance of the destination service in the subscriber/tenant subaccounts. Just destinations (at the subaccount level).

In your case the example destination to test would be **mysaas-dest** assuming you responded yes to the question in the generator: _Would you like to include an example of using the destination reuse service?_

The mysaas-cfapi destination is used internally by the app centrally to create the application routes during the subscription process and is not relevant as a destination for the subscribers themselves.

If you're still having issues perhaps you can share the full project and the details of the destination(s) defined in the subscriber/tenant subaccounts?

Best regards,

Philip

**Comment by chandeep2013** [comment]
Hello Philip,

Please check my code in the git repository below (sample code).

https://github.com/chandeep2013/sample_saas.git

**Destination info:**

**Provider:** :

![Provider1-Destination](https://user-images.githubusercontent.com/37897145/158159130-91b3712a-f190-44ca-a41c-8d3d27684645.PNG)

Consumer1: 
![Consumer1-Destination](https://user-images.githubusercontent.com/37897145/158159183-5cbc1faa-fde2-4da6-b7e1-c448b13b4ed0.PNG)

Provider1 Output:
![image](https://user-images.githubusercontent.com/37897145/158159564-992d65de-3cc7-4ddd-8c77-12f2c48ba939.png)

Consumer1 Output:
![image](https://user-images.githubusercontent.com/37897145/158159741-079dee2f-f3ce-45ee-94be-baecef53b55f.png)


Now we can see both outputs looks same.

Destinations are not picking from Consumer it is picking from Provider.

Regards,
Chamdeep

**Comment by chandeep2013** [comment]
Hello Philip,

Thanks for the update. I just tried with cloud SDK execute method.
![image](https://user-images.githubusercontent.com/37897145/158188859-143cf4b9-a788-4ce1-b920-6f22a8bb73cf.png)

Still, I can see the same response from the Producer and consumer.

From Consumer destination URL is different.

![image](https://user-images.githubusercontent.com/37897145/158189116-e23e8e58-21ae-4174-a323-3e07b944d099.png)

Something I am missing..!!!!


Regards,
Chamdeep

**Comment by chandeep2013** [comment]
Hello,

I am trying to run "/srv/destinations" this service. It is asking the authorization.
![image](https://user-images.githubusercontent.com/37897145/158355889-3a9eb8a0-d01e-4057-94fc-3d6bf03fca7f.png)

How can I get access for this "https://authentication.us10.hana.ondemand.com/login" endpoint?


Regards,
Chamdeep

**Comment by saphanaacademy** [comment]
Hi Chamdeep,

Please see the multitenant [troubleshooting](https://www.youtube.com/watch?v=Gb1DKY1T6Ds&list=PLkzo92owKnVx3Sh0nemX8GoSNzJGfsWJM&index=21) video.

Regards,
Philip

**Comment by chandeep2013** [comment]
> Hello Philip,
> 
> Thanks for the update. I just tried with cloud SDK execute method. ![image](https://user-images.githubusercontent.com/37897145/158188859-143cf4b9-a788-4ce1-b920-6f22a8bb73cf.png)
> 
> Still, I can see the same response from the Producer and consumer.
> 
> From Consumer destination URL is different.
> 
> ![image](https://user-images.githubusercontent.com/37897145/158189116-e23e8e58-21ae-4174-a323-3e07b944d099.png)
> 
> Something I am missing..!!!!
> 
> Regards, Chamdeep

@saphanaacademy can you please help me with this issue?

**Comment by saphanaacademy** [comment]
Hi Chamdeep,

I recommend you set up a clean environment and use the latest version of the generator to scaffold out a project and test from there without making any modifications. Then try to apply your changes one by one to see where things go wrong.

If you still have questions I suggest you ask the [SAP Community](https://answers.sap.com/index.html) where you'll reach a much broader group of experts and where others can more easily find and benefit from the answers.

Feel free to open GitHub issues for the generators should they be crashing or not working in some way or for enhancement requests etc. 

But this is not the right place for general discussion on multitenancy in BTP.

As such I'm closing this issue.

Best regards,
Philip
