### ISSUE TITLE
Do we need standalone/managed app router to get rea.authInfo.checkLocalScope()..?

### ISSUE THREAD

**Issue by chandeep2013** [saphanaacademy/generator-saphanaacademy-saas#5]
Hello,

I am trying to build a multi-tenant application by using the below series of videos on youtube.

https://www.youtube.com/watch?v=E816z61O_S8&list=PLkzo92owKnVx3Sh0nemX8GoSNzJGfsWJM&index=1&ab_channel=SAPHANAAcademy

Do we need standalone/managed app router to get rea.authInfo.checkLocalScope()..?

Or app folder will consider as approuter..?
![image](https://user-images.githubusercontent.com/37897145/160053437-1787e93f-3007-4723-b4c2-7a4ee6188170.png)

I am trying to get scope by using the below methods but I am not getting?
Can you help to get scopes?

console.log("reqObj",req.authInfo);
    console.log("checkLocalScope",req.authInfo.checkLocalScope('admin'));
    console.log("checkLocalScope",req.authInfo.checkLocalScope('enduser'));
    console.log("getGrantType: ",req.authInfo.getGrantType());
    console.log("getAttribute: ",req.authInfo.getAttribute());
    console.log("getAttributes: ",req.authInfo.getAttributes());
    console.log("getConfigType: ",req.authInfo.getConfigType());
    console.log("getUniquePrincipalName: ",req.authInfo.getUniquePrincipalName());
    console.log("getAdditionalAuthAttribute: ",req.authInfo.getAdditionalAuthAttribute());
    console.log("uaaUser",req.authInfo.checkScope('uaa.user'));
    console.log("reqAuthCheck", req.authInfo.checkScope('trtrialbalacesaasapp!t50889.admin'),req.authInfo.checkScope('$XSAPPNAME.enduser'));
    console.log("reqAuthInfoscopes", req.authInfo.scopes);
    console.log("reqAuthInfoscopes",req.authInfo.checkLocalScope("otpdev-trtrialbalacesaasapp!t50889.admin"));
    if (req.authInfo !== undefined && req.authInfo.checkLocalScope("otpdev-trtrialbalacesaasapp!t50889.admin")){
        console.log("checkLocalScope admin");
    }
    if (req.authInfo !== undefined && req.authInfo.checkLocalScope("otpdev-trtrialbalacesaasapp!t50889.enduser")){
        console.log("checkLocalScope User");
    }

Regards,
Chamdeep

**Comment by saphanaacademy** [comment]
Hi Chamdeep,

These are all great questions but this is the wrong place.

Please ask such questions on the [SAP Community](https://answers.sap.com/index.html) where you'll reach a much broader group of experts and where others can more easily find and benefit from the answers.

Feel free to open GitHub issues for the generators should they be crashing or not working in some way or for enhancement requests etc.

But GitHub issues are not the right place for general discussion.

Calls to req.authInfo functions are usually made from a srv module. See the examples in srv/server.js:

```
app.get('/srv/info', function (req, res) {
    if (req.authInfo.checkScope('$XSAPPNAME.User')) {
        let info = {
            'userInfo': req.user,
            'subdomain': req.authInfo.getSubdomain(),
            'tenantId': req.authInfo.getZoneId()
        };
```
This should work fine from here too:

```
        console.log("checkLocalScope",req.authInfo.checkLocalScope('Administrator'));
        console.log("checkLocalScope",req.authInfo.checkLocalScope('User'));
```

Thanks,
Philip
