### ISSUE TITLE
What is the goal of the example in custom.js?

### ISSUE THREAD

**Issue by piejanssens** [saphanaacademy/generator-saphanaacademy-saas#6]
What problem is being solved here? I couldn't figure it out from git blame.
Where/when is TENANT_HOST set in the environment?

**Comment by saphanaacademy** [comment]
Hello @piejanssens ,
TENANT_HOST is used to facilitate "local" development. See this [video tutorial](https://www.youtube.com/watch?v=YCesXwyGG_8&list=PLkzo92owKnVx3Sh0nemX8GoSNzJGfsWJM&index=18&t=373s).
For general Q&A we prefer the [SAP Community](https://answers.sap.com/index.html).
Thanks

**Comment by piejanssens** [comment]
Thanks for clearing that up!
