### ISSUE TITLE
Simplify mta by defining global parameter appname

### ISSUE THREAD

**Issue by piejanssens** [saphanaacademy/generator-saphanaacademy-saas#7]
In line with [SAP Help](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/06c0c9b8036046ef963621aafc44af98.html?locale=en-US) a global mta parameter could be set to define the application name.

This then eliminates the need for the `application` property provided by the html5 app and the`app_api/application` can be replaced by `${appname}`.

I also like in the sample of SAP Help that all resources have a simple name like 'approuter', 'xsuaa' or 'saas-registry' and then consistently use `service-name`.

PS: I don't know why this project is using the name of the space in the `xsappname`, whereas the [SAP Help sample](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/6069e4efa8bc456997c9a25abdb69a43.html?locale=en-US) is just using `${appname}`. Is there a disadvantage for not including the name of the space? 
If we don't need it, then it would be simpler to use `${appname}` and avoid the need for the additional custom parameter `${xsuaa-app}`.

**Comment by saphanaacademy** [comment]
Hello @piejanssens ,
Thanks for your comment and we'll take a look to see if we can further optimize the code that's  generated.
There are often many ways to achieve the same thing and the capabilities of global MTA parameters (and BTP in general) are  constantly evolving.
Also please note that the doc you refer to is for the ABAP Environment whereas the generator focuses on the Cloud Foundry environment.
For general Q&A we prefer the [SAP Community](https://answers.sap.com/index.html).
Thanks

**Comment by saphanaacademy** [comment]
Hello @piejanssens ,
Certain inter-service dependency requirements in mta.yaml are no longer needed as BTP has evolved so version 0.0.16 takes this into account and includes some simplification of mta.yaml. You can see the changes [here](https://github.com/saphanaacademy/generator-saphanaacademy-saas/commit/4d2d6ad87026b1a076c056231cfd073c30e868df#diff-edb3dcbd67e7d79f58060573af994fee7c78b2735b7893990a6ff9709a4f8e1a).
Thanks.
